package langost

type LangCode struct {
	Lang              string
	ISO_639_1         []string
	ISO_639_2         []string
	ISO_639_3         []string
	GOST_7_75__97_lat []string
	GOST_7_75__97_cyr []string
	Code              int
}

func ByCode(code int) LangCode {
	lang := LangCode{"Неидентифицированный", []string{"—"}, []string{"und"}, []string{"und"}, []string{"und"}, []string{"унд"}, 480}
	switch code {
	case -1:
		code = 480
	}
	for _, lan := range LangList {
		if lan.Code == code {
			return lan
		}
	}
	return lang
}

func ByName(name string) LangCode {
	lang := LangCode{"Неидентифицированный", []string{"—"}, []string{"und"}, []string{"und"}, []string{"und"}, []string{"унд"}, 480}
	for _, lan := range LangList {
		if lan.Lang == name {
			return lan
		}
	}
	return lang
}

func ByLat(lat string) LangCode {
	lang := LangCode{"Неидентифицированный", []string{"—"}, []string{"und"}, []string{"und"}, []string{"und"}, []string{"унд"}, 480}
	for _, lan := range LangList {
		for _, la := range lan.GOST_7_75__97_lat {
			if la == lat {
				return lan
			}
		}
	}
	return lang
}

func ByCyr(cyr string) LangCode {
	lang := LangCode{"Неидентифицированный", []string{"—"}, []string{"und"}, []string{"und"}, []string{"und"}, []string{"унд"}, 480}
	for _, lan := range LangList {
		for _, la := range lan.GOST_7_75__97_cyr {
			if la == cyr {
				return lan
			}
		}
	}
	return lang
}

//Язык	ISO 639-1	ISO 639-2	ISO 639-3	ГОСТ 7.75-97 (лат.)	ГОСТ 7.75-97 (кир.)	Цифровой код
var LangList = []LangCode{
	{"Абазинский", []string{"—"}, []string{"—"}, []string{"abq"}, []string{"aba"}, []string{"аба"}, 5},
	{"Абхазский", []string{"ab"}, []string{"abk"}, []string{"abk"}, []string{"abk"}, []string{"абх"}, 10},
	{"Авадхи", []string{"—"}, []string{"awa"}, []string{"awa"}, []string{"awa"}, []string{"авд"}, 12},
	{"Аварский", []string{"av"}, []string{"ava"}, []string{"ava"}, []string{"ava"}, []string{"ава"}, 14},
	{"Авестийский", []string{"ae"}, []string{"ave"}, []string{"ave"}, []string{"ave"}, []string{"аве"}, 16},
	{"Адангме", []string{"—"}, []string{"ada"}, []string{"ada"}, []string{"ada"}, []string{"ада"}, 18},
	{"Адыгейский", []string{"—"}, []string{"ady"}, []string{"ady"}, []string{"ady"}, []string{"ады"}, 20},
	{"Азербайджанский", []string{"az"}, []string{"aze"}, []string{"aze"}, []string{"aze"}, []string{"азе"}, 25},
	{"Аймара", []string{"ay"}, []string{"aym"}, []string{"aym"}, []string{"aym"}, []string{"айм"}, 26},
	{"Айну", []string{"—"}, []string{"ain"}, []string{"ain"}, []string{"—"}, []string{"—"}, -1},
	{"Акан", []string{"ak"}, []string{"aka"}, []string{"aka"}, []string{"aka"}, []string{"ака"}, 27},
	{"Аккадский", []string{"—"}, []string{"akk"}, []string{"akk"}, []string{"akk"}, []string{"акк"}, 28},
	{"Албанский", []string{"sq"}, []string{"alb", "sqi"}, []string{"sqi"}, []string{"alb", "sqi"}, []string{"алб"}, 30},
	{"Алеутский", []string{"—"}, []string{"ale"}, []string{"ale"}, []string{"ale"}, []string{"але"}, 33},
	{"Алтайский", []string{"—"}, []string{"alt"}, []string{"alt"}, []string{"alt"}, []string{"алт"}, 35},
	{"Амхарский", []string{"am"}, []string{"amh"}, []string{"amh"}, []string{"amh"}, []string{"амх"}, 40},
	{"Английский", []string{"en"}, []string{"eng"}, []string{"eng"}, []string{"eng"}, []string{"анг"}, 45},
	{"Арабский", []string{"ar"}, []string{"ara"}, []string{"ara"}, []string{"ara"}, []string{"ара"}, 50},
	{"Аравакский", []string{"—"}, []string{"arw"}, []string{"arw"}, []string{"arw"}, []string{"арв"}, 51},
	{"Арамейский", []string{"—"}, []string{"arc"}, []string{"arc"}, []string{"—"}, []string{"арс"}, 52},
	{"Арапахо", []string{"—"}, []string{"arp"}, []string{"arp"}, []string{"arp"}, []string{"арп"}, 53},
	{"Арауканский", []string{"—"}, []string{"arn"}, []string{"arn"}, []string{"arn"}, []string{"арн"}, 54},
	{"Армянский", []string{"hy"}, []string{"arm", "hye"}, []string{"hye", "axm", "xcl"}, []string{"arm", "hye"}, []string{"арм"}, 55},
	{"Ассамский", []string{"as"}, []string{"asm"}, []string{"asm"}, []string{"asm"}, []string{"аса"}, 60},
	{"Ассирийский", []string{"—"}, []string{"—"}, []string{"aii"}, []string{"ass"}, []string{"асс"}, 65},
	{"Атапачские", []string{"—"}, []string{"—"}, []string{"ath"}, []string{"ath"}, []string{"ата"}, 67},
	{"Афарский", []string{"aa"}, []string{"aar"}, []string{"aar"}, []string{"aar"}, []string{"афа"}, 68},
	{"Африкаанс", []string{"af"}, []string{"afr"}, []string{"afr"}, []string{"afr"}, []string{"афр"}, 70},
	{"Африхили", []string{"—"}, []string{"afh"}, []string{"afh"}, []string{"afh"}, []string{"афх"}, 73},
	{"Ахвахский", []string{"—"}, []string{"akv"}, []string{"akv"}, []string{"akh"}, []string{"ахв"}, 74},
	{"Ацтекский", []string{"—"}, []string{"—"}, []string{"nah"}, []string{"—"}, []string{"ацт"}, 75},
	{"Ачехский", []string{"—"}, []string{"ace"}, []string{"ace"}, []string{"ace"}, []string{"аче"}, 76},
	{"Ачоли", []string{"—"}, []string{"ach"}, []string{"ach"}, []string{"ach"}, []string{"ачо"}, 77},
	{"Балийский", []string{"—"}, []string{"ban"}, []string{"ban"}, []string{"ban"}, []string{"бал"}, 78},
	{"Бамбара", []string{"bm"}, []string{"bam"}, []string{"bam"}, []string{"bam"}, []string{"бам"}, 80},
	{"Банда", []string{"—"}, []string{"bad"}, []string{"bad"}, []string{"bad"}, []string{"бан"}, 82},
	{"Баса", []string{"—"}, []string{"bas"}, []string{"bas"}, []string{"bas"}, []string{"бас"}, 84},
	{"Баскский", []string{"eu"}, []string{"baq", "eus"}, []string{"eus"}, []string{"baq", "eus"}, []string{"бак"}, 85},
	{"Башкирский", []string{"ba"}, []string{"bak"}, []string{"bak"}, []string{"bak"}, []string{"баш"}, 86},
	{"Беджа", []string{"—"}, []string{"bej"}, []string{"bej"}, []string{"bej"}, []string{"бед"}, 87},
	{"Белорусский", []string{"be"}, []string{"bel"}, []string{"bel"}, []string{"bel"}, []string{"бел"}, 90},
	{"Белуджский", []string{"—"}, []string{"bal"}, []string{"bal"}, []string{"bal"}, []string{"беу"}, 95},
	{"Бемба", []string{"—"}, []string{"bem"}, []string{"bem"}, []string{"bem"}, []string{"бем"}, 97},
	{"Бенгальский", []string{"bn"}, []string{"ben"}, []string{"ben"}, []string{"ben"}, []string{"бен"}, 100},
	{"Бикольский", []string{"—"}, []string{"bik", "bcl"}, []string{"bik"}, []string{"bik"}, []string{"бик"}, 103},
	{"Бини", []string{"—"}, []string{"bin"}, []string{"bin"}, []string{"bin"}, []string{"бин"}, 104},
	{"Бирманский", []string{"my"}, []string{"bur", "mya"}, []string{"mya"}, []string{"bur", "mya"}, []string{"бир"}, 105},
	{"Бислама", []string{"bi"}, []string{"bis"}, []string{"bis"}, []string{"bis"}, []string{"бис"}, 107},
	{"Болгарский", []string{"bg"}, []string{"bul"}, []string{"bul"}, []string{"bul"}, []string{"бол"}, 115},
	{"Боснийский", []string{"bs"}, []string{"bos"}, []string{"bos"}, []string{"—"}, []string{"бос"}, -1},
	{"Брауи", []string{"—"}, []string{"—"}, []string{"brh"}, []string{"bra"}, []string{"бра"}, 117},
	{"Бретонский", []string{"br"}, []string{"bre"}, []string{"bre"}, []string{"bre"}, []string{"бре"}, 120},
	{"Бугийский", []string{"—"}, []string{"bug"}, []string{"bug"}, []string{"bug"}, []string{"буг"}, 123},
	{"Бурятский", []string{"—"}, []string{"bua"}, []string{"bua"}, []string{"bua"}, []string{"бур"}, 125},
	{"Бходжпури", []string{"—"}, []string{"bho"}, []string{"bho"}, []string{"bho"}, []string{"бхо"}, 126},
	{"Ваи", []string{"—"}, []string{"vai"}, []string{"vai"}, []string{"vai"}, []string{"ваи"}, 127},
	{"Валлийский", []string{"cy"}, []string{"cym", "wel"}, []string{"cym"}, []string{"cym", "wel"}, []string{"вал"}, 130},
	{"Варай", []string{"—"}, []string{"war"}, []string{"war"}, []string{"war"}, []string{"вар"}, 131},
	{"Вашо", []string{"—"}, []string{"was"}, []string{"was"}, []string{"was"}, []string{"ваш"}, 132},
	{"Венгерский", []string{"hu"}, []string{"hun"}, []string{"hun"}, []string{"hun"}, []string{"вен"}, 133},
	{"Венда", []string{"ve"}, []string{"ven"}, []string{"ven"}, []string{"ven"}, []string{"вед"}, 134},
	{"Вепсский", []string{"—"}, []string{"—"}, []string{"vep"}, []string{"vep"}, []string{"веп"}, 135},
	{"Воламо", []string{"—"}, []string{"wal"}, []string{"wal"}, []string{"wal"}, []string{"воа"}, 136},
	{"Волапюк", []string{"vo"}, []string{"vol"}, []string{"vol"}, []string{"vol"}, []string{"вол"}, 137},
	{"Волоф", []string{"wo"}, []string{"wol"}, []string{"wol"}, []string{"wol"}, []string{"воф"}, 138},
	{"Вьетнамский", []string{"vi"}, []string{"vie"}, []string{"vie"}, []string{"vie"}, []string{"вье"}, 140},
	{"Га", []string{"—"}, []string{"gaa"}, []string{"gaa"}, []string{"gaa"}, []string{"гаа"}, 142},
	{"Гавайский", []string{"—"}, []string{"haw"}, []string{"haw"}, []string{"haw"}, []string{"гав"}, 143},
	{"Гагаузский", []string{"—"}, []string{"—"}, []string{"gag"}, []string{"gag"}, []string{"гаг"}, 145},
	{"Гайо", []string{"—"}, []string{"gay"}, []string{"gay"}, []string{"gay"}, []string{"гай"}, 146},
	{"Галисийский", []string{"gl"}, []string{"glg"}, []string{"glg"}, []string{"glg"}, []string{"гал"}, 147},
	{"Ганда", []string{"lg"}, []string{"lug"}, []string{"lug"}, []string{"lug"}, []string{"ган"}, 148},
	{"Гереро", []string{"hz"}, []string{"her"}, []string{"her"}, []string{"her"}, []string{"гер"}, 149},
	{"Геэз", []string{"—"}, []string{"gez"}, []string{"gez"}, []string{"gez"}, []string{"гез"}, 151},
	{"Гилбертский", []string{"—"}, []string{"gil"}, []string{"gil"}, []string{"gil"}, []string{"гил"}, 152},
	{"Гонди", []string{"—"}, []string{"gon"}, []string{"gon"}, []string{"gon"}, []string{"гон"}, 153},
	{"Готский", []string{"—"}, []string{"got"}, []string{"got"}, []string{"got"}, []string{"гот"}, 154},
	{"Гребо", []string{"—"}, []string{"grb"}, []string{"grb"}, []string{"grb"}, []string{"грб"}, 155},
	{"Гренландский", []string{"kl"}, []string{"kal"}, []string{"kal"}, []string{"kal"}, []string{"эсм"}, 843},
	{"Греческий (новогреческий)", []string{"el"}, []string{"ell", "gre"}, []string{"ell"}, []string{"ell", "gre"}, []string{"гре"}, 157},
	{"Грузинский", []string{"ka"}, []string{"geo", "kat"}, []string{"kat"}, []string{"geo", "kat"}, []string{"гру"}, 158},
	{"Гуарани", []string{"gn"}, []string{"grn"}, []string{"grn"}, []string{"grn"}, []string{"гуа"}, 160},
	{"Гуджарати", []string{"gu"}, []string{"guj"}, []string{"guj"}, []string{"guj"}, []string{"гуд"}, 165},
	{"Гэльский", []string{"gd"}, []string{"gla"}, []string{"gla"}, []string{"gae", "gdh"}, []string{"гэл"}, 170},
	{"Дакота", []string{"—"}, []string{"dak"}, []string{"dak"}, []string{"dak"}, []string{"дак"}, 173},
	{"Даргинский", []string{"—"}, []string{"dar"}, []string{"dar"}, []string{"dag"}, []string{"даг"}, 175},
	{"Дари", []string{"—"}, []string{"prs"}, []string{"prs"}, []string{"—"}, []string{"—"}, -1},
	{"Датский", []string{"da"}, []string{"dan"}, []string{"dan"}, []string{"dan"}, []string{"дат"}, 178},
	{"Делавэрский", []string{"—"}, []string{"del"}, []string{"del"}, []string{"del"}, []string{"дел"}, 179},
	{"Дзонг-кэ", []string{"dz"}, []string{"dzo"}, []string{"dzo"}, []string{"dzo"}, []string{"дзо"}, 183},
	{"Дивехи (Мальдивский)", []string{"dv"}, []string{"div"}, []string{"div"}, []string{"div"}, []string{"див"}, 180},
	{"Динка", []string{"—"}, []string{"din"}, []string{"din"}, []string{"din"}, []string{"дин"}, 181},
	{"Диула (Дьюла)", []string{"—"}, []string{"dyu"}, []string{"dyu"}, []string{"dyu"}, []string{"диу"}, 182},
	{"Догри", []string{"—"}, []string{"doi"}, []string{"doi"}, []string{"doi"}, []string{"дои"}, 184},
	{"Древнегреческий", []string{"—"}, []string{"grc"}, []string{"grc"}, []string{"grc"}, []string{"дрг"}, 186},
	{"Древнеегипетский", []string{"—"}, []string{"egy"}, []string{"egy"}, []string{"egy"}, []string{"дре"}, 187},
	{"Древнерусский", []string{"—"}, []string{"—"}, []string{"orv"}, []string{"rua"}, []string{"дрр"}, 188},
	{"Древнесаксонский", []string{"—"}, []string{"—"}, []string{"osx"}, []string{"—"}, []string{"—"}, -1},
	{"Дуала", []string{"—"}, []string{"dua"}, []string{"dua"}, []string{"dua"}, []string{"дуа"}, 190},
	{"Дунганский", []string{"—"}, []string{"—"}, []string{"dng"}, []string{"dun"}, []string{"дун"}, 191},
	{"Еврейско-арабский", []string{"—"}, []string{"jrb"}, []string{"jrb"}, []string{"jrb"}, []string{"еар"}, 192},
	{"Еврейско-персидский", []string{"—"}, []string{"jpr"}, []string{"jpr"}, []string{"jpr"}, []string{"епе"}, 193},
	{"Зенагский", []string{"—"}, []string{"zen"}, []string{"zen"}, []string{"zen"}, []string{"зен"}, 194},
	{"Зулу", []string{"zu"}, []string{"zul"}, []string{"zul"}, []string{"zul"}, []string{"зул"}, 195},
	{"Зуньи", []string{"—"}, []string{"zun"}, []string{"zun"}, []string{"zun"}, []string{"зун"}, 196},
	{"Ибанский", []string{"—"}, []string{"iba"}, []string{"iba"}, []string{"iba"}, []string{"иба"}, 197},
	{"Иврит", []string{"he"}, []string{"heb"}, []string{"heb"}, []string{"heb"}, []string{"ивр"}, 198},
	{"Игбо", []string{"ig"}, []string{"ibo"}, []string{"ibo"}, []string{"ibo"}, []string{"ибо"}, 199},
	{"Идиш", []string{"yi"}, []string{"yid"}, []string{"yid"}, []string{"yid"}, []string{"иди"}, 202},
	{"Илоко", []string{"—"}, []string{"ilo"}, []string{"ilo"}, []string{"ilo"}, []string{"ило"}, 203},
	{"Ингушский", []string{"—"}, []string{"inh"}, []string{"inh"}, []string{"ing"}, []string{"инг"}, 205},
	{"Индонезийский", []string{"id"}, []string{"ind"}, []string{"ind"}, []string{"ind"}, []string{"инд"}, 210},
	{"Интерлингва", []string{"ia"}, []string{"ina"}, []string{"ina"}, []string{"ina"}, []string{"ина"}, 215},
	{"Интерлингве", []string{"ie"}, []string{"ile"}, []string{"ile"}, []string{"ile"}, []string{"ине"}, 216},
	{"Инуктитут", []string{"iu"}, []string{"iku"}, []string{"iku"}, []string{"iku"}, []string{"инк"}, 217},
	{"Инупиак", []string{"ik"}, []string{"ipk"}, []string{"ipk"}, []string{"ipk"}, []string{"инп"}, 218},
	{"Ирландский", []string{"ga"}, []string{"gle"}, []string{"gle"}, []string{"gai", "iri"}, []string{"ирл"}, 220},
	{"Исландский", []string{"is"}, []string{"ice", "isl"}, []string{"isl"}, []string{"ice", "isl"}, []string{"исл"}, 225},
	{"Испанский", []string{"es"}, []string{"esl", "spa"}, []string{"spa"}, []string{"esl", "spa"}, []string{"исп"}, 230},
	{"Итальянский", []string{"it"}, []string{"ita"}, []string{"ita"}, []string{"ita"}, []string{"ита"}, 235},
	{"Ительменский", []string{"—"}, []string{"—"}, []string{"itl"}, []string{"ite"}, []string{"ите"}, 240},
	{"Йоруба", []string{"yo"}, []string{"yor"}, []string{"yor"}, []string{"yor"}, []string{"йор"}, 245},
	{"Кабардино-черкесский", []string{"—"}, []string{"kbd"}, []string{"kbd"}, []string{"kad"}, []string{"каа"}, 250},
	{"Кабильский", []string{"—"}, []string{"kab"}, []string{"kab"}, []string{"kab"}, []string{"каб"}, 251},
	{"Кави", []string{"—"}, []string{"kaw"}, []string{"kaw"}, []string{"kaw"}, []string{"каг"}, 252},
	{"Каддо", []string{"—"}, []string{"cad"}, []string{"cad"}, []string{"cad"}, []string{"кад"}, 254},
	{"Казахский", []string{"kk"}, []string{"kaz"}, []string{"kaz"}, []string{"kaz"}, []string{"каз"}, 255},
	{"Калмыцкий", []string{"—"}, []string{"xal"}, []string{"xal"}, []string{"kal"}, []string{"кал"}, 260},
	{"Камба", []string{"—"}, []string{"kam"}, []string{"kam"}, []string{"kam"}, []string{"кам"}, 263},
	{"Каннада", []string{"kn"}, []string{"kan"}, []string{"kan"}, []string{"kan"}, []string{"кан"}, 265},
	{"Канури", []string{"kr"}, []string{"kau"}, []string{"kau"}, []string{"kau"}, []string{"кау"}, 267},
	{"Караимский", []string{"—"}, []string{"—"}, []string{"kdr"}, []string{"kai"}, []string{"каи"}, 270},
	{"Каракалпакский", []string{"—"}, []string{"kaa"}, []string{"kaa"}, []string{"kaa"}, []string{"кап"}, 275},
	{"Карачаево-балкарский", []string{"—"}, []string{"krc"}, []string{"krc"}, []string{"kah"}, []string{"као"}, 280},
	{"Карельский", []string{"—"}, []string{"krl"}, []string{"krl"}, []string{"kae"}, []string{"кас"}, 285},
	{"Кариб", []string{"—"}, []string{"car"}, []string{"car"}, []string{"car"}, []string{"кар"}, 288},
	{"Каталанский", []string{"ca"}, []string{"cat"}, []string{"cat"}, []string{"cat"}, []string{"кат"}, 290},
	{"Качинский", []string{"—"}, []string{"kac"}, []string{"kac"}, []string{"kac"}, []string{"кач"}, 293},
	{"Кашмири", []string{"ks"}, []string{"kas"}, []string{"kas"}, []string{"kas"}, []string{"каш"}, 294},
	{"Кечуа", []string{"qu"}, []string{"que"}, []string{"que"}, []string{"que"}, []string{"кеч"}, 300},
	{"Кикуйю", []string{"ki"}, []string{"kik"}, []string{"kik"}, []string{"kik"}, []string{"кик"}, 302},
	{"Киньяма", []string{"kj"}, []string{"kua"}, []string{"kua"}, []string{"kua"}, []string{"кия"}, 303},
	{"Киргизский", []string{"ky"}, []string{"kir"}, []string{"kir"}, []string{"kyr"}, []string{"кир", "кыр"}, 305},
	{"Китайский", []string{"zh"}, []string{"chi", "zho"}, []string{"zho"}, []string{"chi", "zho"}, []string{"кит"}, 315},
	{"Клингонский", []string{"—"}, []string{"tlh"}, []string{"tlh"}, []string{"—"}, []string{"—"}, -1},
	{"Коми", []string{"kv"}, []string{"kom"}, []string{"kom"}, []string{"kom"}, []string{"кои"}, 320},
	{"Коми-пермяцкий", []string{"—"}, []string{"—"}, []string{"koi"}, []string{"pem"}, []string{"ком"}, 325},
	{"Конго", []string{"kg"}, []string{"kon"}, []string{"kon"}, []string{"kon"}, []string{"кон"}, 326},
	{"Конкани", []string{"—"}, []string{"kok"}, []string{"kok"}, []string{"kok"}, []string{"кок"}, 327},
	{"Коптский", []string{"—"}, []string{"cop"}, []string{"cop"}, []string{"cop"}, []string{"коп"}, 328},
	{"Корейский", []string{"ko"}, []string{"kor"}, []string{"kor"}, []string{"kor"}, []string{"коо"}, 330},
	{"Корнский", []string{"kw"}, []string{"cor"}, []string{"cor"}, []string{"cor"}, []string{"кор"}, 332},
	{"Корсиканский", []string{"co"}, []string{"cos"}, []string{"cos"}, []string{"cos"}, []string{"кос"}, 334},
	{"Корякский", []string{"—"}, []string{"—"}, []string{"kpy"}, []string{"koy"}, []string{"коя"}, 335},
	{"Коса", []string{"xh"}, []string{"xho"}, []string{"xho"}, []string{"xho"}, []string{"коа"}, 340},
	{"Кпелле", []string{"—"}, []string{"kpe"}, []string{"kpe"}, []string{"kpe"}, []string{"кпе"}, 341},
	{"Крик", []string{"—"}, []string{"mus"}, []string{"mus"}, []string{"mus"}, []string{"крк"}, 344},
	{"Крымскотатарский", []string{"—"}, []string{"crh"}, []string{"crh"}, []string{"cri"}, []string{"кры"}, 347},
	{"Кумыкский", []string{"—"}, []string{"kum"}, []string{"kum"}, []string{"kum"}, []string{"кум"}, 349},
	{"Курдский", []string{"ku"}, []string{"kur"}, []string{"kur"}, []string{"kur"}, []string{"кур"}, 350},
	{"Курух", []string{"—"}, []string{"kru"}, []string{"kru"}, []string{"kru"}, []string{"куу"}, 352},
	{"Кусайе", []string{"—"}, []string{"kos"}, []string{"kos"}, []string{"kus"}, []string{"кус"}, 353},
	{"Кутенай", []string{"—"}, []string{"kut"}, []string{"kut"}, []string{"kut"}, []string{"кут"}, 354},
	{"Кхаси", []string{"—"}, []string{"kha"}, []string{"kha"}, []string{"kha"}, []string{"кха"}, 357},
	{"Кхмерский", []string{"km"}, []string{"khm"}, []string{"khm"}, []string{"khm"}, []string{"кхм"}, 360},
	{"Ладино", []string{"—"}, []string{"lad"}, []string{"lad"}, []string{"lad"}, []string{"лад"}, 363},
	{"Лакский", []string{"—"}, []string{"—"}, []string{"lbe"}, []string{"lak"}, []string{"лак"}, 370},
	{"Ламба", []string{"—"}, []string{"lam"}, []string{"lam"}, []string{"lam"}, []string{"лам"}, 373},
	{"Лаосский", []string{"lo"}, []string{"lao"}, []string{"lao"}, []string{"lao"}, []string{"лао"}, 375},
	{"Латинский", []string{"la"}, []string{"lat"}, []string{"lat"}, []string{"lat"}, []string{"лат"}, 380},
	{"Латышский", []string{"lv"}, []string{"lav"}, []string{"lav"}, []string{"lav"}, []string{"лаш"}, 385},
	{"Лахнда", []string{"—"}, []string{"lah"}, []string{"lah"}, []string{"lah"}, []string{"лах"}, 387},
	{"Лезгинский", []string{"—"}, []string{"lez"}, []string{"lez"}, []string{"lez"}, []string{"лез"}, 390},
	{"Лингала", []string{"ln"}, []string{"lin"}, []string{"lin"}, []string{"lin"}, []string{"лин"}, 395},
	{"Литовский", []string{"lt"}, []string{"lit"}, []string{"lit"}, []string{"lit"}, []string{"лит"}, 400},
	{"Лози", []string{"—"}, []string{"loz"}, []string{"loz"}, []string{"loz"}, []string{"лоз"}, 402},
	{"Луба-катанга", []string{"lu"}, []string{"lub"}, []string{"lub"}, []string{"lub"}, []string{"луб"}, 404},
	{"Луисеньо", []string{"—"}, []string{"lui"}, []string{"lui"}, []string{"lui"}, []string{"луи"}, 406},
	{"Лунда", []string{"—"}, []string{"lun"}, []string{"lun"}, []string{"lun"}, []string{"лун"}, 407},
	{"Луо", []string{"—"}, []string{"luo"}, []string{"luo"}, []string{"luo"}, []string{"луо"}, 408},
	{"Люксембургский", []string{"lb"}, []string{"ltz"}, []string{"ltz"}, []string{"ltz"}, []string{"люк"}, 409},
	{"Магахи", []string{"—"}, []string{"mag"}, []string{"mag"}, []string{"mag"}, []string{"маг"}, 410},
	{"Мадурский", []string{"—"}, []string{"mad"}, []string{"mad"}, []string{"mad"}, []string{"мад"}, 411},
	{"Майтхили", []string{"—"}, []string{"mai"}, []string{"mai"}, []string{"mai"}, []string{"май"}, 412},
	{"Макассарский", []string{"—"}, []string{"mak"}, []string{"mak"}, []string{"mak"}, []string{"мак"}, 414},
	{"Македонский", []string{"mk"}, []string{"mac", "mkd"}, []string{"mkd"}, []string{"mac", "mke"}, []string{"маа"}, 415},
	{"Малагасийский", []string{"mg"}, []string{"mlg"}, []string{"mlg"}, []string{"mlg"}, []string{"млг"}, 418},
	{"Малайский", []string{"ms"}, []string{"may", "msa"}, []string{"msa"}, []string{"may", "msa"}, []string{"маз"}, 420},
	{"Малаялам", []string{"ml"}, []string{"mal"}, []string{"mal"}, []string{"mal"}, []string{"мал"}, 425},
	{"Мальтийский", []string{"mt"}, []string{"mlt"}, []string{"mlt"}, []string{"mlt"}, []string{"млт"}, 430},
	{"Мандинго", []string{"—"}, []string{"man"}, []string{"man"}, []string{"man"}, []string{"маи"}, 432},
	{"Манипури", []string{"—"}, []string{"mni"}, []string{"mni"}, []string{"mni"}, []string{"мни"}, 433},
	{"Мансийский (Вогульский)", []string{"—"}, []string{"—"}, []string{"mns"}, []string{"vog"}, []string{"ман"}, 435},
	{"Маори", []string{"mi"}, []string{"mao", "mri"}, []string{"mri"}, []string{"mao", "mri"}, []string{"мао"}, 437},
	{"Маратхи", []string{"mr"}, []string{"mar"}, []string{"mar"}, []string{"mar"}, []string{"мар"}, 440},
	{"Марвари", []string{"—"}, []string{"mwr"}, []string{"mwr"}, []string{"mwr"}, []string{"мвр"}, 443},
	{"Марийский (черемисский)", []string{"—"}, []string{"chm"}, []string{"chm"}, []string{"chm"}, []string{"мач"}, 445},
	{"Маршалльский", []string{"mh"}, []string{"mah"}, []string{"mah"}, []string{"mah"}, []string{"маш"}, 446},
	{"Масаи", []string{"—"}, []string{"mas"}, []string{"mas"}, []string{"mas"}, []string{"мас"}, 447},
	{"Межславянский", []string{"—"}, []string{"—"}, []string{"isv"}, []string{"—"}, []string{"—"}, -1},
	{"Менде", []string{"—"}, []string{"men"}, []string{"men"}, []string{"men"}, []string{"мен"}, 451},
	{"Мерянский", []string{"me"}, []string{"mer"}, []string{"mer"}, []string{"—"}, []string{"мер"}, -1},
	{"Микмак", []string{"—"}, []string{"mic"}, []string{"mic"}, []string{"mic"}, []string{"мик"}, 452},
	{"Минангкабау", []string{"—"}, []string{"min"}, []string{"min"}, []string{"min"}, []string{"мин"}, 453},
	{"Мокшанский", []string{"—"}, []string{"mdf"}, []string{"mdf"}, []string{"mok"}, []string{"мок"}, 455},
	{"Молдавский", []string{"mo"}, []string{"mol"}, []string{"mol"}, []string{"mol"}, []string{"мол"}, 460},
	{"Монго", []string{"—"}, []string{"lol"}, []string{"lol"}, []string{"lol"}, []string{"мог"}, 462},
	{"Монгольский", []string{"mn"}, []string{"mon"}, []string{"mon"}, []string{"mon"}, []string{"мон"}, 463},
	{"Мооре", []string{"—"}, []string{"mos"}, []string{"mos"}, []string{"mos"}, []string{"мос"}, 466},
	{"Мохаук", []string{"—"}, []string{"moh"}, []string{"moh"}, []string{"moh"}, []string{"мох"}, 467},
	{"Мэнский (Мэнкский)", []string{"gv"}, []string{"glv"}, []string{"glv"}, []string{"max"}, []string{"мэн"}, 469},
	{"Навахо", []string{"nv"}, []string{"nav"}, []string{"nav"}, []string{"nav"}, []string{"нав"}, 470},
	{"Нанайский (гольдский)", []string{"—"}, []string{"—"}, []string{"gld"}, []string{"—"}, []string{"нан"}, 471},
	{"Науру", []string{"na"}, []string{"nau"}, []string{"nau"}, []string{"nau"}, []string{"нау"}, 472},
	{"Ндебеле северный", []string{"nd"}, []string{"nde"}, []string{"nde"}, []string{"nde"}, []string{"нде"}, 473},
	{"Ндебеле южный", []string{"nr"}, []string{"nbl"}, []string{"nbl"}, []string{"nbl"}, []string{"нбл"}, 474},
	{"Ндунга", []string{"ng"}, []string{"ndo"}, []string{"ndo"}, []string{"ndo"}, []string{"нду"}, 475},
	{"Неварский", []string{"—"}, []string{"new"}, []string{"new"}, []string{"new"}, []string{"нев"}, 478},
	{"Неидентифицированный", []string{"—"}, []string{"und"}, []string{"und"}, []string{"und"}, []string{"унд"}, 480},
	{"Немецкий", []string{"de"}, []string{"deu", "ger"}, []string{"deu"}, []string{"deu", "ger"}, []string{"нем"}, 481},
	{"Ненецкий (юрако-самоедский)", []string{"—"}, []string{"—"}, []string{"yrk"}, []string{"yur"}, []string{"нен"}, 482},
	{"Непальский", []string{"ne"}, []string{"nep"}, []string{"nep"}, []string{"nep"}, []string{"неп"}, 485},
	{"Нзима", []string{"—"}, []string{"nzi"}, []string{"nzi"}, []string{"nzi"}, []string{"нзи"}, 487},
	{"Нивхский (гиляцкий)", []string{"—"}, []string{"—"}, []string{"niv"}, []string{"giy"}, []string{"нив"}, 490},
	{"Нидерландский (Голландский)", []string{"nl"}, []string{"dut", "nld"}, []string{"nld"}, []string{"dut", "ndl"}, []string{"нид"}, 495},
	{"Нидерландский средневековый", []string{"—"}, []string{"dum"}, []string{"dum"}, []string{"dum"}, []string{"нис"}, 496},
	{"Ниуэ", []string{"—"}, []string{"niu"}, []string{"niu"}, []string{"niu"}, []string{"ниу"}, 498},
	{"Ногайский", []string{"—"}, []string{"nog"}, []string{"nog"}, []string{"nog"}, []string{"ног"}, 505},
	{"Норвежский", []string{"no"}, []string{"nor"}, []string{"nor"}, []string{"nor"}, []string{"нор"}, 506},
	{"Ньоро", []string{"—"}, []string{"nyo"}, []string{"nyo"}, []string{"nyo"}, []string{"ньо"}, 508},
	{"Ньямвези", []string{"—"}, []string{"nym"}, []string{"nym"}, []string{"nym"}, []string{"ням"}, 509},
	{"Ньянджа", []string{"ny"}, []string{"nya"}, []string{"nya"}, []string{"nya"}, []string{"нян"}, 510},
	{"Ньянколе", []string{"—"}, []string{"nyn"}, []string{"nyn"}, []string{"nyn"}, []string{"нья"}, 512},
	{"Нюнорск (новонорвежский)", []string{"nn"}, []string{"nno"}, []string{"nno"}, []string{"nno"}, []string{"нно"}, 513},
	{"Оджибве", []string{"oj"}, []string{"oji"}, []string{"oji"}, []string{"oji"}, []string{"одж"}, 515},
	{"Окситанский", []string{"oc"}, []string{"oci"}, []string{"oci"}, []string{"oci"}, []string{"окс"}, 517},
	{"Ория", []string{"or"}, []string{"ori"}, []string{"ori"}, []string{"ori"}, []string{"ори"}, 520},
	{"Оромо", []string{"om"}, []string{"orm"}, []string{"orm"}, []string{"orm"}, []string{"орм"}, 522},
	{"Оседжи", []string{"—"}, []string{"osa"}, []string{"osa"}, []string{"osa"}, []string{"осе"}, 523},
	{"Осетинский", []string{"os"}, []string{"oss"}, []string{"oss"}, []string{"oss"}, []string{"ост"}, 524},
	{"Палау", []string{"—"}, []string{"pau"}, []string{"pau"}, []string{"pau"}, []string{"пал"}, 526},
	{"Пали", []string{"pi"}, []string{"pli"}, []string{"pli"}, []string{"pli"}, []string{"пли"}, 527},
	{"Пампанга", []string{"—"}, []string{"pam"}, []string{"pam"}, []string{"pam"}, []string{"пам"}, 528},
	{"Пангасинан", []string{"—"}, []string{"pag"}, []string{"pag"}, []string{"pag"}, []string{"паг"}, 529},
	{"Пенджабский", []string{"pa"}, []string{"pan"}, []string{"pan"}, []string{"pan"}, []string{"пан"}, 530},
	{"Папьяменто", []string{"—"}, []string{"pap"}, []string{"pap"}, []string{"pap"}, []string{"пап"}, 533},
	{"Персидский", []string{"fa"}, []string{"fas", "per"}, []string{"fas"}, []string{"fas", "per"}, []string{"пер"}, 535},
	{"Пехлевийский", []string{"—"}, []string{"pal"}, []string{"pal"}, []string{"pal"}, []string{"пех"}, 537},
	{"Польский", []string{"pl"}, []string{"pol"}, []string{"pol"}, []string{"pol"}, []string{"пол"}, 540},
	{"Понапе", []string{"—"}, []string{"pon"}, []string{"pon"}, []string{"pon"}, []string{"пон"}, 542},
	{"Португальский", []string{"pt"}, []string{"por"}, []string{"por"}, []string{"роr"}, []string{"пор"}, 545},
	{"Пушту", []string{"ps"}, []string{"pus"}, []string{"pus"}, []string{"pus"}, []string{"пуш"}, 550},
	{"Раджастхани", []string{"—"}, []string{"raj"}, []string{"raj"}, []string{"raj"}, []string{"рад"}, 555},
	{"Разных семей языки", []string{"—"}, []string{"mul"}, []string{"mul"}, []string{"mul"}, []string{"мул"}, 556},
	{"Раротонга", []string{"—"}, []string{"rar"}, []string{"rar"}, []string{"rar"}, []string{"рар"}, 557},
	{"Ретороманский", []string{"rm"}, []string{"roh"}, []string{"roh"}, []string{"—"}, []string{"рет"}, 560},
	{"Руанда", []string{"rw"}, []string{"kin"}, []string{"kin"}, []string{"kin"}, []string{"кин"}, 304},
	{"Румынский", []string{"ro"}, []string{"ron", "rum"}, []string{"ron"}, []string{"ron", "rum"}, []string{"рум"}, 565},
	{"Рунди", []string{"rn"}, []string{"run"}, []string{"run"}, []string{"run"}, []string{"рун"}, 567},
	{"Русский", []string{"ru"}, []string{"rus"}, []string{"rus"}, []string{"rus"}, []string{"рус"}, 570},
	{"Рутульский", []string{"—"}, []string{"—"}, []string{"rut"}, []string{"—"}, []string{"рут"}, -1},
	{"Саамский", []string{"—"}, []string{"smi"}, []string{"smi"}, []string{"smi"}, []string{"саа"}, 575},
	{"Самаритянский арамейский", []string{"—"}, []string{"sam"}, []string{"sam"}, []string{"sam"}, []string{"сам"}, 577},
	{"Самоанский", []string{"sm"}, []string{"smo"}, []string{"smo"}, []string{"smo"}, []string{"смо"}, 578},
	{"Санго", []string{"sg"}, []string{"sag"}, []string{"sag"}, []string{"sag"}, []string{"саг"}, 579},
	{"Сандаве", []string{"—"}, []string{"sad"}, []string{"sad"}, []string{"sad"}, []string{"сад"}, 580},
	{"Санскрит", []string{"sa"}, []string{"san"}, []string{"san"}, []string{"san"}, []string{"сан"}, 581},
	{"Сапотекский", []string{"—"}, []string{"zap"}, []string{"zap"}, []string{"zap"}, []string{"сап"}, 582},
	{"Сардинский", []string{"sc"}, []string{"srd"}, []string{"srd"}, []string{"srd"}, []string{"срд"}, 583},
	{"Свази", []string{"ss"}, []string{"ssw"}, []string{"ssw"}, []string{"ssw"}, []string{"сва"}, 584},
	{"Себуано", []string{"—"}, []string{"ceb"}, []string{"ceb"}, []string{"ceb"}, []string{"себ"}, 587},
	{"Селькупский", []string{"—"}, []string{"sel"}, []string{"sel"}, []string{"sel"}, []string{"сел"}, 590},
	{"Сербский", []string{"sr"}, []string{"scc"}, []string{"srp"}, []string{"—"}, []string{"—"}, -1},
	{"Серер", []string{"—"}, []string{"srr"}, []string{"srr"}, []string{"srr"}, []string{"срр"}, 596},
	{"Сидама", []string{"—"}, []string{"sid"}, []string{"sid"}, []string{"sid"}, []string{"сид"}, 597},
	{"Сиксика", []string{"—"}, []string{"bla"}, []string{"bla"}, []string{"bla"}, []string{"сик"}, 598},
	{"Сингальский", []string{"si"}, []string{"sin"}, []string{"sin"}, []string{"sin"}, []string{"син"}, 599},
	{"Синдхи", []string{"sd"}, []string{"snd"}, []string{"snd"}, []string{"snd"}, []string{"снд"}, 600},
	{"Сирийский", []string{"—"}, []string{"syr"}, []string{"syr"}, []string{"syr"}, []string{"сир"}, 602},
	{"Словацкий", []string{"sk"}, []string{"slk", "slo"}, []string{"slk"}, []string{"slk", "slo"}, []string{"сло"}, 605},
	{"Словенский", []string{"sl"}, []string{"slv"}, []string{"slv"}, []string{"slv"}, []string{"слв"}, 610},
	{"Согдийский", []string{"—"}, []string{"sog"}, []string{"sog"}, []string{"sog"}, []string{"сог"}, 613},
	{"Сомали", []string{"so"}, []string{"som"}, []string{"som"}, []string{"som"}, []string{"сом"}, 615},
	{"Сото северный", []string{"—"}, []string{"nso"}, []string{"nso"}, []string{"nso"}, []string{"сос"}, 617},
	{"Сото южный", []string{"st"}, []string{"sot"}, []string{"sot"}, []string{"sot"}, []string{"сот"}, 618},
	{"Среднеанглийский", []string{"—"}, []string{"enm"}, []string{"enm"}, []string{"enm"}, []string{"сра"}, 619},
	{"Средневерхненемецкий", []string{"—"}, []string{"gmh"}, []string{"gmh"}, []string{"gmh"}, []string{"срн"}, 620},
	{"Среднеирландский", []string{"—"}, []string{"mga"}, []string{"mga"}, []string{"mga"}, []string{"сеи"}, 621},
	{"Среднефранцузский", []string{"—"}, []string{"frm"}, []string{"frm"}, []string{"frm"}, []string{"срф"}, 622},
	{"Староанглийский", []string{"—"}, []string{"ang"}, []string{"ang"}, []string{"ang"}, []string{"ста"}, 623},
	{"Староверхненемецкий", []string{"—"}, []string{"goh"}, []string{"goh"}, []string{"goh"}, []string{"свн"}, 624},
	{"Староирландский", []string{"—"}, []string{"sga"}, []string{"sga"}, []string{"sga"}, []string{"сти"}, 625},
	{"Старонорвежский", []string{"—"}, []string{"non"}, []string{"non"}, []string{"non"}, []string{"стн"}, 626},
	{"Староперсидский", []string{"—"}, []string{"peo"}, []string{"peo"}, []string{"peo"}, []string{"стп"}, 627},
	{"Старопровансальский", []string{"—"}, []string{"pro"}, []string{"pro"}, []string{"pro"}, []string{"спр"}, 628},
	{"Старотурецкий", []string{"—"}, []string{"ota"}, []string{"ota"}, []string{"ota"}, []string{"стт"}, 629},
	{"Старофранцузский", []string{"—"}, []string{"fro"}, []string{"fro"}, []string{"fro"}, []string{"стф"}, 630},
	{"Суахили", []string{"sw"}, []string{"swa"}, []string{"swa"}, []string{"swa"}, []string{"суа"}, 631},
	{"Сукума", []string{"—"}, []string{"suk"}, []string{"suk"}, []string{"suk"}, []string{"сук"}, 632},
	{"Сунданский", []string{"su"}, []string{"sun"}, []string{"sun"}, []string{"sun"}, []string{"сун"}, 633},
	{"Сусу", []string{"—"}, []string{"sus"}, []string{"sus"}, []string{"sus"}, []string{"сус"}, 634},
	{"Табасаранский", []string{"—"}, []string{"—"}, []string{"tab"}, []string{"tab"}, []string{"таб"}, 635},
	{"Тагальский", []string{"tl"}, []string{"tgl"}, []string{"tgl"}, []string{"tgl"}, []string{"таг"}, 636},
	{"Таджикский", []string{"tg"}, []string{"tgk"}, []string{"tgk"}, []string{"tgk"}, []string{"тад"}, 640},
	{"Тайский", []string{"th"}, []string{"tha"}, []string{"tha"}, []string{"tha"}, []string{"таи"}, 645},
	{"Таитянский", []string{"ty"}, []string{"tah"}, []string{"tah"}, []string{"tah"}, []string{"тая"}, 647},
	{"Талышский", []string{"—"}, []string{"—"}, []string{"tly"}, []string{"tal"}, []string{"тал"}, 650},
	{"Тамашек", []string{"—"}, []string{"tmh"}, []string{"tmh"}, []string{"tmh"}, []string{"тмш"}, 653},
	{"Тамильский", []string{"ta"}, []string{"tam"}, []string{"tam"}, []string{"tam"}, []string{"там"}, 655},
	{"Татарский", []string{"tt"}, []string{"tat"}, []string{"tat"}, []string{"tat"}, []string{"тар"}, 660},
	{"Тви", []string{"tw"}, []string{"twi"}, []string{"twi"}, []string{"twi"}, []string{"тви"}, 670},
	{"Телугу", []string{"te"}, []string{"tel"}, []string{"tel"}, []string{"tel"}, []string{"тел"}, 675},
	{"Темне", []string{"—"}, []string{"tem"}, []string{"tem"}, []string{"tem"}, []string{"тем"}, 677},
	{"Терено", []string{"—"}, []string{"ter"}, []string{"ter"}, []string{"ter"}, []string{"тер"}, 678},
	{"Тибетский", []string{"bo"}, []string{"bod", "tib"}, []string{"bod"}, []string{"bod", "tib"}, []string{"тиб"}, 680},
	{"Тиви", []string{"—"}, []string{"tiw"}, []string{"tiw"}, []string{"tiv"}, []string{"тив"}, 681},
	{"Тигре", []string{"—"}, []string{"tig"}, []string{"tig"}, []string{"tig"}, []string{"тиг"}, 682},
	{"Тигринья", []string{"ti"}, []string{"tir"}, []string{"tir"}, []string{"tir"}, []string{"тир"}, 683},
	{"Тлингит", []string{"—"}, []string{"tli"}, []string{"tli"}, []string{"tli"}, []string{"тли"}, 684},
	{"Тонга (Ньяса)", []string{"—"}, []string{"tog"}, []string{"tog"}, []string{"tog"}, []string{"тог"}, 685},
	{"Тонганский", []string{"to"}, []string{"ton"}, []string{"ton"}, []string{"ton"}, []string{"тон"}, 686},
	{"Трукский", []string{"—"}, []string{"—"}, []string{"chk"}, []string{"tru"}, []string{"тру"}, 687},
	{"Тсвана", []string{"tn"}, []string{"tsn"}, []string{"tsn"}, []string{"tsn"}, []string{"тсн"}, 688},
	{"Тсонга", []string{"ts"}, []string{"tso"}, []string{"tso"}, []string{"tso"}, []string{"тсо"}, 689},
	{"Тувинский", []string{"—"}, []string{"tyv"}, []string{"tyv"}, []string{"tyv"}, []string{"тув"}, 690},
	{"Тумбука", []string{"—"}, []string{"tum"}, []string{"tum"}, []string{"tum"}, []string{"тум"}, 692},
	{"Турецкий", []string{"tr"}, []string{"tur"}, []string{"tur"}, []string{"tur"}, []string{"тур"}, 693},
	{"Туркменский", []string{"tk"}, []string{"tuk"}, []string{"tuk"}, []string{"tuk"}, []string{"тук"}, 695},
	{"Угаритский", []string{"—"}, []string{"uga"}, []string{"uga"}, []string{"uga"}, []string{"уга"}, 697},
	{"Удмуртский (вотяцкий)", []string{"—"}, []string{"udm"}, []string{"udm"}, []string{"vot"}, []string{"удм"}, 700},
	{"Удэгейский", []string{"—"}, []string{"—"}, []string{"ude"}, []string{"ude"}, []string{"удэ"}, 705},
	{"Узбекский", []string{"uz"}, []string{"uzb"}, []string{"uzb"}, []string{"uzb"}, []string{"узб"}, 710},
	{"Уйгурский", []string{"ug"}, []string{"uig"}, []string{"uig"}, []string{"uig"}, []string{"уйг"}, 715},
	{"Украинский", []string{"uk"}, []string{"ukr"}, []string{"ukr"}, []string{"ukr"}, []string{"укр"}, 720},
	{"Ульчский", []string{"—"}, []string{"—"}, []string{"ulc"}, []string{"ulc"}, []string{"уль"}, 725},
	{"Умбунду", []string{"—"}, []string{"umb"}, []string{"umb"}, []string{"umb"}, []string{"умб"}, 727},
	{"Урду", []string{"ur"}, []string{"urd"}, []string{"urd"}, []string{"urd"}, []string{"урд"}, 730},
	{"Фанг", []string{"—"}, []string{"fan"}, []string{"fan"}, []string{"fan"}, []string{"фан"}, 732},
	{"Фанти", []string{"—"}, []string{"fat"}, []string{"fat"}, []string{"fat"}, []string{"фат"}, 733},
	{"Фарерский", []string{"fo"}, []string{"fao"}, []string{"fao"}, []string{"fao"}, []string{"фар"}, 735},
	{"Фиджи", []string{"fj"}, []string{"fij"}, []string{"fij"}, []string{"fij"}, []string{"фид"}, 737},
	{"Филиппинский", []string{"fl"}, []string{"fil"}, []string{"fil"}, []string{"tgl"}, []string{"таг"}, 636},
	{"Финикийский", []string{"—"}, []string{"phn"}, []string{"phn"}, []string{"phn"}, []string{"фик"}, 738},
	{"Финский (Suomi)", []string{"fi"}, []string{"fin"}, []string{"fin"}, []string{"fin"}, []string{"фин"}, 740},
	{"Фон", []string{"—"}, []string{"fon"}, []string{"fon"}, []string{"fon"}, []string{"фон"}, 743},
	{"Французский", []string{"fr"}, []string{"fra", "fre"}, []string{"fra"}, []string{"fra", "fre"}, []string{"фра"}, 745},
	{"Фризский", []string{"fy"}, []string{"fry"}, []string{"fry"}, []string{"fry"}, []string{"фри"}, 750},
	{"Фулах", []string{"ff"}, []string{"ful"}, []string{"ful"}, []string{"ful"}, []string{"фул"}, 752},
	{"Хайда", []string{"—"}, []string{"hai"}, []string{"hai"}, []string{"hai"}, []string{"хай"}, 753},
	{"Хакасский", []string{"—"}, []string{"—"}, []string{"kjh"}, []string{"khk"}, []string{"хак"}, 755},
	{"Хантыйский (остяцкий)", []string{"—"}, []string{"—"}, []string{"kca"}, []string{"ost"}, []string{"хан"}, 760},
	{"Хауса", []string{"ha"}, []string{"hau"}, []string{"hau"}, []string{"hau"}, []string{"хау"}, 761},
	{"Хилигайнон", []string{"—"}, []string{"hil"}, []string{"hil"}, []string{"hil"}, []string{"хил"}, 762},
	{"Хинди", []string{"hi"}, []string{"hin"}, []string{"hin"}, []string{"hin"}, []string{"хин"}, 770},
	{"Хиримоту", []string{"ho"}, []string{"hmo"}, []string{"hmo"}, []string{"hmo"}, []string{"хмо"}, 772},
	{"Хорватский", []string{"hr"}, []string{"hrv", "scr"}, []string{"hrv"}, []string{"—"}, []string{"—"}, -1},
	{"Хотанский", []string{"—"}, []string{"kho"}, []string{"kho"}, []string{"kho"}, []string{"хот"}, 773},
	{"Хупа", []string{"—"}, []string{"hup"}, []string{"hup"}, []string{"hup"}, []string{"хуп"}, 774},
	{"Цахурский", []string{"—"}, []string{"—"}, []string{"tkr"}, []string{"tsa"}, []string{"цах"}, 775},
	{"Церковнославянский (Старославянский)", []string{"cu"}, []string{"chu"}, []string{"chu"}, []string{"chu"}, []string{"цер"}, 777},
	{"Цимшиан", []string{"—"}, []string{"tsi"}, []string{"tsi"}, []string{"tsi"}, []string{"цим"}, 778},
	{"Цыганский", []string{"—"}, []string{"rom"}, []string{"rom"}, []string{"rom"}, []string{"цыг"}, 780},
	{"Чагатайский", []string{"—"}, []string{"chg"}, []string{"chg"}, []string{"chg"}, []string{"чаг"}, 781},
	{"Чаморро", []string{"ch"}, []string{"cha"}, []string{"cha"}, []string{"cha"}, []string{"чам"}, 782},
	{"Шайенн (Чейенн)", []string{"—"}, []string{"chy"}, []string{"chy"}, []string{"chy"}, []string{"чей"}, 783},
	{"Чероки", []string{"—"}, []string{"chr"}, []string{"chr"}, []string{"chr"}, []string{"чер"}, 784},
	{"Чеченский", []string{"ce"}, []string{"che"}, []string{"che"}, []string{"che"}, []string{"чеч"}, 785},
	{"Чешский", []string{"cs"}, []string{"ces", "cze"}, []string{"ces"}, []string{"ces", "cze"}, []string{"чеш"}, 790},
	{"Чжуанский", []string{"za"}, []string{"zha"}, []string{"zha"}, []string{"zha"}, []string{"чжу"}, 791},
	{"Чибча", []string{"—"}, []string{"chb"}, []string{"chb"}, []string{"chb"}, []string{"чиб"}, 792},
	{"Чинук жаргон", []string{"—"}, []string{"chn"}, []string{"chn"}, []string{"chn"}, []string{"чин"}, 793},
	{"Чоктав", []string{"—"}, []string{"cho"}, []string{"cho"}, []string{"cho"}, []string{"чок"}, 794},
	{"Чувашский", []string{"cv"}, []string{"chv"}, []string{"chv"}, []string{"chv"}, []string{"чув"}, 795},
	{"Чукотский", []string{"—"}, []string{"—"}, []string{"ckt"}, []string{"chk"}, []string{"чук"}, 800},
	{"Шанский", []string{"—"}, []string{"shn"}, []string{"shn"}, []string{"shn"}, []string{"шан"}, 803},
	{"Шведский", []string{"sv"}, []string{"sve", "swe"}, []string{"swe"}, []string{"sve", "swe"}, []string{"шве"}, 805},
	{"Шона", []string{"sn"}, []string{"sna"}, []string{"sna"}, []string{"sna"}, []string{"шон"}, 807},
	{"Шорский", []string{"—"}, []string{"—"}, []string{"cjs"}, []string{"sho"}, []string{"шор"}, 810},
	{"Шотландский (англо-шотландский)", []string{"—"}, []string{"sco"}, []string{"sco"}, []string{"—"}, []string{"—"}, -1},
	{"Шугнанский", []string{"—"}, []string{"—"}, []string{"sgh"}, []string{"shu"}, []string{"шуг"}, 815},
	{"Шумерский", []string{"—"}, []string{"sux"}, []string{"sux"}, []string{"sux"}, []string{"шум"}, 817},
	{"Эве", []string{"ee"}, []string{"ewe"}, []string{"ewe"}, []string{"ewe"}, []string{"эве"}, 820},
	{"Эвенкийский (тунгусский)", []string{"—"}, []string{"—"}, []string{"evn"}, []string{"tum"}, []string{"эвк"}, 825},
	{"Эвенский", []string{"—"}, []string{"—"}, []string{"eve"}, []string{"lau"}, []string{"эвн"}, 830},
	{"Эвондо", []string{"—"}, []string{"ewo"}, []string{"ewo"}, []string{"ewo"}, []string{"эво"}, 832},
	{"Экаджук", []string{"—"}, []string{"eka"}, []string{"eka"}, []string{"eka"}, []string{"эка"}, 833},
	{"Эламский", []string{"—"}, []string{"elx"}, []string{"elx"}, []string{"elx"}, []string{"эла"}, 834},
	{"Эрзянский", []string{"—"}, []string{"myv"}, []string{"myv"}, []string{"erz"}, []string{"эрз"}, 835},
	{"Эсперанто", []string{"eo"}, []string{"epo"}, []string{"epo"}, []string{"epo"}, []string{"эсп"}, 845},
	{"Эстонский", []string{"et"}, []string{"est"}, []string{"est"}, []string{"est"}, []string{"эст"}, 850},
	{"Эфик", []string{"—"}, []string{"efi"}, []string{"efi"}, []string{"efi"}, []string{"эфи"}, 852},
	{"Яванский", []string{"jv"}, []string{"jav", "jaw"}, []string{"jav"}, []string{"jav", "jaw"}, []string{"ява"}, 860},
	{"Якутский (Саха)", []string{"—"}, []string{"sah"}, []string{"sah"}, []string{"sah"}, []string{"яку"}, 865},
	{"Яо", []string{"—"}, []string{"yao"}, []string{"yao"}, []string{"yao"}, []string{"яоа"}, 867},
	{"Яп", []string{"—"}, []string{"yap"}, []string{"yap"}, []string{"yap"}, []string{"япа"}, 868},
	{"Японский", []string{"ja"}, []string{"jpn"}, []string{"jpn"}, []string{"jpn"}, []string{"япо"}, 870},
}
